---
title: "Research Tips"

So how does one even get started with research? Maybe you're coming out from undergrad and have no idea what you're doing? Maybe you chose to take a gap year or two and are now coming back and have no idea what to do? Maybe you have an idea, but just don't know how to execute it? If any of these scenerios fit you, then these tips are for you. 

1. What can you see yourself doing in 10 years? 
2. Where would you like to make a change? 
3. What interests you the most? 
4. What does your PI do? Can you connect your ideas to their research? 
5. What is your 5 year goal? How you can make this research fit into that? 
6. Have you explored multiple pathways? The first idea isn't always the greatest. 
7. Meet with your advisor. It's literally their job to help you with finding your footing. 
8. It doesn't have to be complicated. 
9. Do you understand the details? Make a power point and present it to yourself. 
10. If you can't decide, just choose a path and go with it.
